name: Generate keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
          -keystore my-upload-key.jks \
          -alias upload \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass password123 \
          -keypass password123 \
          -dname "CN=Willykez,O=WillyShare,C=TZ"

      - name: Encode keystore
        run: |
          base64 -w 0 my-upload-key.jks > keystore.txt
          cat keystore.txt
